### ISSUE TITLE
Not working in rspec 3.5

### ISSUE THREAD

**Issue by chrishough** [bonzofenix/cancun#1]
I am starting to build a spec using this example and it is completely failing...
```ruby
require 'cancun'
describe 'myapp:data:load ->' do
  include Cancun::Highline
  before { init_highline_test }
  include_context 'rake'


  let(:task_name) { 'myapp:data:load:from' }
  let(:path_to_task) { 'tasks/data' }

  describe ':from', focus: true do
    it 'processes from a specified starting point' do
      execute(invoke_task).and_type('2017-01-01')
      invoke_task
      binding.pry

    end
  end
end
```
rspec output
```
  1) myapp:data:load -> :from processes from a specified starting point
     Failure/Error: before { init_highline_test }

     NameError:
       undefined local variable or method `init_highline_test' for #<RSpec::ExampleGroups::MyappDataLoad::From:0x007f9bf7192298>```
